In [1]:
import pandas as pd
import numpy as py

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [4]:
for i in dir(movies):
    if not i[0] == "_" : print(i)

T
abs
add
add_prefix
add_suffix
agg
aggregate
align
all
any
apply
applymap
asfreq
asof
assign
astype
at
at_time
attrs
axes
backfill
between_time
bfill
bool
boxplot
budget
clip
columns
combine
combine_first
compare
convert_dtypes
copy
corr
corrwith
count
cov
cummax
cummin
cumprod
cumsum
describe
diff
div
divide
dot
drop
drop_duplicates
droplevel
dropna
dtypes
duplicated
empty
eq
equals
eval
ewm
expanding
explode
ffill
fillna
filter
first
first_valid_index
flags
floordiv
from_dict
from_records
ge
genres
get
groupby
gt
head
hist
homepage
iat
id
idxmax
idxmin
iloc
index
infer_objects
info
insert
interpolate
isetitem
isin
isna
isnull
items
iterrows
itertuples
join
keys
keywords
kurt
kurtosis
last
last_valid_index
le
loc
lt
map
mask
max
mean
median
melt
memory_usage
merge
min
mod
mode
mul
multiply
ndim
ne
nlargest
notna
notnull
nsmallest
nunique
original_language
original_title
overview
pad
pct_change
pipe
pivot
pivot_table
plot
pop
popularity
pow
prod
product
production_companies
production

In [5]:
movies2 = movies.merge(credits,on='title')

In [6]:
print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)


In [7]:
movies2.original_language.value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [8]:
movies2.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  ... runtime  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title vote_average vote_count movie_id  \
0  Enter the World of Pandora.  Avatar          7.2      11800    19995   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  

[1 rows x 23 columns]

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [10]:
# columns that matter
impCols = ['genres','id','keywords','title','overview','cast','crew']

In [11]:
movies2 = movies2[impCols]

In [12]:
movies2.sample()

genres      id  \
3572  [{"id": 27, "name": "Horror"}, {"id": 53, "nam...  227348   

                                               keywords  \
3572  [{"id": 6152, "name": "supernatural"}, {"id": ...   

                                     title  \
3572  Paranormal Activity: The Marked Ones   

                                               overview  \
3572  Seventeen-year-old Jesse has been hearing terr...   

                                                   cast  \
3572  [{"cast_id": 21, "character": "Jesse Arista", ...   

                                                   crew  
3572  [{"credit_id": "5345887c0e0a267bcd001f50", "de...

In [13]:
movies2.keywords[0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [14]:
movies2.shape

(4809, 7)

In [15]:
movies2.isna().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [16]:
movies2.dropna(inplace=True)

In [17]:
movies2.duplicated().sum()

0

In [18]:
# movies2.iloc[0].genres

#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# convert format into list of names

def convertFormat(obj, limit=0):
    return [n['name'] for n in eval(obj)][:limit] if limit else [n['name'] for n in eval(obj)]
    
# convertFormat(movies2.iloc[0].genres)

In [19]:
movies2.genres = movies2.genres.apply(convertFormat)

In [20]:
movies2.head(1)

genres     id  \
0  [Action, Adventure, Fantasy, Science Fiction]  19995   

                                            keywords   title  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...  Avatar   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [21]:
movies2.keywords = movies2.keywords.apply(convertFormat)

In [22]:
movies2.cast = movies2.cast.apply(convertFormat,args=(3,))

In [23]:
def getDirector(obj,job='Director'):
    return [n['name'] for n in eval(obj) if n['job'] == job]

# movies2.crew.apply(getDirector)

In [24]:
movies2.crew = movies2.crew.apply(getDirector)

In [25]:
movies2.head(1)

genres     id  \
0  [Action, Adventure, Fantasy, Science Fiction]  19995   

                                            keywords   title  \
0  [culture clash, future, space war, space colon...  Avatar   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                                               cast             crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]  [James Cameron]

In [26]:
movies2.overview=movies2.overview.apply(lambda x: x.split())

In [27]:
def removeWS(obj):
    return [n.replace(' ','') for n in obj]

In [28]:
movies2.genres=movies2.genres.apply(removeWS)
movies2.keywords=movies2.keywords.apply(removeWS)
movies2.cast=movies2.cast.apply(removeWS)
movies2.crew=movies2.crew.apply(removeWS)

In [29]:
movies2.head(2)

genres     id  \
0  [Action, Adventure, Fantasy, ScienceFiction]  19995   
1                  [Adventure, Fantasy, Action]    285   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   

                                      title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                            cast             crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]   [JamesCameron]  
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]  [GoreVerbinski]

In [30]:
movies2['tags'] = movies2.overview+movies2.keywords+movies2.cast+movies2.crew

In [31]:
movies2.columns

Index(['genres', 'id', 'keywords', 'title', 'overview', 'cast', 'crew',
       'tags'],
      dtype='object')

In [32]:
movies3 = movies2[['id','title','tags']]

In [33]:
movies3.head(1)

id   title                                               tags
0  19995  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...

In [34]:
movies3.tags=movies3.tags.apply(lambda x: " ".join(x))

C:\Users\jynts\AppData\Local\Temp\ipykernel_12572\3256881877.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies3.tags=movies3.tags.apply(lambda x: " ".join(x))


In [35]:
movies3.tags=movies3.tags.apply(lambda x: x.lower())

C:\Users\jynts\AppData\Local\Temp\ipykernel_12572\3270373427.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies3.tags=movies3.tags.apply(lambda x: x.lower())


In [36]:
movies3.tags[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [37]:
movies3.head(1)

id   title                                               tags
0  19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [64]:
from nltk.stem.porter import PorterStemmer 
ps = PorterStemmer()
# steming -> 
# [love, loving, lovely] converts into one entity

In [65]:
# example
ps.stem('loved')

'love'

In [66]:
def stem(text):
    return " ".join([ps.stem(t) for t in text.split()])

In [67]:
movies3['tags']=movies3['tags'].apply(stem)

C:\Users\jynts\AppData\Local\Temp\ipykernel_12572\2693404502.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies3['tags']=movies3['tags'].apply(stem)


In [68]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [69]:
vectors = cv.fit_transform(movies3['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [70]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [71]:
from sklearn.metrics.pairwise import cosine_similarity

In [74]:
similarity = cosine_similarity(vectors)
print(similarity)
print(similarity.shape)

[[1.         0.         0.03184649 ... 0.02475369 0.         0.        ]
 [0.         1.         0.         ... 0.02592379 0.         0.0277137 ]
 [0.03184649 0.         1.         ... 0.02680281 0.         0.        ]
 ...
 [0.02475369 0.02592379 0.02680281 ... 1.         0.0412393  0.04454354]
 [0.         0.         0.         ... 0.0412393  1.         0.08817334]
 [0.         0.0277137  0.         ... 0.04454354 0.08817334 1.        ]]
(4806, 4806)


In [91]:
def recommand(movie):
    index = movies3[movies3['title'] == movie].index[0]
    distances = similarity[index]
    similar_movies = sorted(list(enumerate(distances)), reverse=True,key=lambda x:x[1])
    movie_name = [movies3.iloc[m[0]].title for m in similar_movies[1:6]]
    return movie_name

In [92]:
recommand('Batman Begins')

['The Dark Knight',
 'Batman',
 'Batman',
 'Batman v Superman: Dawn of Justice',
 'Synecdoche, New York']